### ISSUE TITLE
How to use this in Swift?

### ISSUE THREAD

**Issue by heshanlk** [quentinhayot/QHSpeechSynthesizerQueue#1]
How can I use this library in Swift?

**Comment by quentinhayot** [comment]
Hi @heshanlk !
I don't have the time to re-write it to Swift at the moment, but you can use a bridging header to use Objective C code in your Swift project.
Look at this answer on SO: http://stackoverflow.com/a/24005242/598812

Tell me if you managed to make it work ;)
