### ISSUE TITLE
Can change the synthethizer voice ? 

### ISSUE THREAD

**Issue by JockerGG** [quentinhayot/QHSpeechSynthesizerQueue#2]
i'm using your library, and is awesome, but i have a little question, is posible to change the voice? 

Thanks for your reply.

Best regards.

**Comment by quentinhayot** [comment]
Hi !
This library is wrapped around iOS tts engine that uses Siri’s voice.
You might be able to select a male or female voice from Siri's settings but:
1) I'm not sure if it will apply to in-apps tts
2) You won't be able to set it from your code anyway

**Comment by quentinhayot** [comment]
I'm closing this for now. Feel free to reopen if you need more info.

**Comment by JockerGG** [comment]
Thanks!!!!
